typography_spectrum: 0.9324788148514926
color:
  brandStrength: 0.36104935873299837
  lightness: 0.775428875349462
  saturation: 0.9425258422270417
  rhythmicContrast: 0.8514825969468802
  brandColors:
    - '#115C7D'
    - '#39A7DA'
    - '#95BE22'
    - '#FFFFFF'
    - '#08182D'
layout_spectrum: 0.08839515829458833
name: MIMETAS
title: organ-on-a-chip. now.
description: predictive tissue- and disease models
