layout_spectrum: 0.08839515829458833
typography_spectrum: 0.9324788148514926
color:
  brandStrength: 0.36104935873299837
  lightness: 0.775428875349462
  saturation: 0.9425258422270417
  rhythmicContrast: 0.8514825969468802
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: MIMETAS
